### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by iPaulPro** [blokadaorg/six-ios#3] opened 2023-07-04 06:57 UTC
What happened to this project? iOS app is completely broken. Cloud-based blocking? RIP

**Comment by balboah** [comment] 2023-07-05 07:56
Hello,

I'm sorry to hear that you're having issues with our iOS app. Could you provide more details about what exactly is broken? The more specifics you can provide, the better we'll be able to assist you.

If you think the issue is related to our Blokada Cloud service, please feel free to reach out to our dedicated support team. You can do so either by sending an email to hello@blokada.org or through the in-app question mark icon.

We're committed to resolving any issues and improving your experience with Blokada.
Thank you for your patience!

**Closed** 2023-07-09 16:44 UTC
